import type { ThemeType } from "../../../config/GameConfig";

export interface LayerConfig {
  asset: string;
  scrollFactor: number;
  depth: number;
  screenX?: number;
  screenY: number;
  opacity: number;
  tintKey: string;
  atmosphericBlend: number;
}

export const THEME_LAYERS: Record<ThemeType, LayerConfig[]> = {
  forest: [
    {
      asset: "cloudLayerB2",
      scrollFactor: 0.01,
      depth: -95,
      screenY: 275,
      opacity: 0.4,
      tintKey: "cloud",
      atmosphericBlend: 0.7,
    },
    {
      asset: "hillsLarge",
      scrollFactor: 0.05,
      depth: -75,
      screenY: 380,
      screenX: 200,
      opacity: 0.75,
      tintKey: "hill",
      atmosphericBlend: 0.9,
    },
    {
      asset: "cloudLayerB1",
      scrollFactor: 0.05,
      depth: -73,
      screenY: 550,
      opacity: 0.4,
      tintKey: "cloud",
      atmosphericBlend: 0.7,
    },
    {
      asset: "hillsLarge",
      scrollFactor: 0.1,
      depth: -70,
      screenY: 600,
      screenX: -150,
      opacity: 0.75,
      tintKey: "hill",
      atmosphericBlend: 0.51,
    },
    {
      asset: "hills",
      scrollFactor: 0.3,
      depth: -58,
      screenY: 850,
      opacity: 0.75,
      tintKey: "hill",
      atmosphericBlend: 0.5,
    },
    {
      asset: "groundLayer2",
      scrollFactor: 0.9,
      depth: -42,
      screenY: 1400,
      opacity: 0.8,
      tintKey: "ground",
      atmosphericBlend: 0.15,
    },
  ],
  desert: [
    {
      asset: "cloudLayerB2",
      scrollFactor: 0.01,
      depth: -95,
      screenY: 600,
      opacity: 0.35,
      tintKey: "cloud",
      atmosphericBlend: 0.95,
    },
    {
      asset: "mountains",
      scrollFactor: 0.05,
      depth: -92,
      screenY: 600,
      opacity: 0.75,
      tintKey: "mountain",
      atmosphericBlend: 0.85,
    },
    {
      asset: "mountains",
      scrollFactor: 0.1,
      depth: -68,
      screenY: 750,
      screenX: 400,
      opacity: 0.75,
      tintKey: "skyMid2",
      atmosphericBlend: 0.5,
    },
    {
      asset: "hills",
      scrollFactor: 0.3,
      depth: -36,
      screenY: 1010,
      screenX: 225,
      opacity: 0.75,
      tintKey: "atmosphereNear",
      atmosphericBlend: 0.7,
    },
    {
      asset: "groundLayer1",
      scrollFactor: 0.9,
      depth: -34,
      screenY: 1500,
      opacity: 0.75,
      tintKey: "atmosphereNear",
      atmosphericBlend: 1,
    },
  ],
  castle: [
    {
      asset: "cloudLayerB2",
      scrollFactor: 0.01,
      depth: -95,
      screenY: 200,
      screenX: 400,
      opacity: 0.3,
      tintKey: "cloud",
      atmosphericBlend: 0.7,
    },
    {
      asset: "cloudLayerB1",
      scrollFactor: 0.05,
      depth: -88,
      screenY: 250,
      screenX: -100,
      opacity: 0.35,
      tintKey: "cloud",
      atmosphericBlend: 0.55,
    },
    {
      asset: "hills",
      scrollFactor: 0.1,
      depth: -85,
      screenY: 380,
      screenX: -150,
      opacity: 0.5,
      tintKey: "hill",
      atmosphericBlend: 0.32,
    },
    {
      asset: "cloudLayer1",
      scrollFactor: 0.1,
      depth: -80,
      screenY: 500,
      screenX: 600,
      opacity: 0.45,
      tintKey: "cloud",
      atmosphericBlend: 0.4,
    },
    {
      asset: "cloudLayer2",
      scrollFactor: 0.15,
      depth: -68,
      screenY: 700,
      screenX: 250,
      opacity: 0.5,
      tintKey: "cloud",
      atmosphericBlend: 0.25,
    },
    {
      asset: "hillsLarge",
      scrollFactor: 0.25,
      depth: -62,
      screenY: 800,
      screenX: 150,
      opacity: 0.6,
      tintKey: "hill",
      atmosphericBlend: 0.18,
    },
    {
      asset: "cloudLayer1",
      scrollFactor: 0.35,
      depth: -55,
      screenY: 950,
      screenX: 800,
      opacity: 0.55,
      tintKey: "cloud",
      atmosphericBlend: 0.12,
    },
    {
      asset: "groundLayer1",
      scrollFactor: 0.9,
      depth: -34,
      screenY: 1400,
      opacity: 0.75,
      tintKey: "ground",
      atmosphericBlend: 0.2,
    },
  ],
  ice: [
    {
      asset: "mountains",
      scrollFactor: 0.05,
      depth: -92,
      screenY: 200,
      screenX: -750,
      opacity: 0.5,
      tintKey: "mountain",
      atmosphericBlend: 0.9,
    },
    {
      asset: "cloudLayerB1",
      scrollFactor: 0.1,
      depth: -88,
      screenY: 350,
      opacity: 0.5,
      tintKey: "cloud",
      atmosphericBlend: 0.55,
    },
    {
      asset: "mountains",
      scrollFactor: 0.15,
      depth: -60,
      screenY: 450,
      screenX: -1200,
      opacity: 0.7,
      tintKey: "mountain",
      atmosphericBlend: 0.7,
    },
    {
      asset: "mountains",
      scrollFactor: 0.2,
      depth: -50,
      screenY: 650,
      screenX: 1375,
      opacity: 0.7,
      tintKey: "mountain",
      atmosphericBlend: 0.6,
    },
    {
      asset: "mountains",
      scrollFactor: 0.35,
      depth: -40,
      screenY: 825,
      screenX: 600,
      opacity: 0.8,
      tintKey: "mountain",
      atmosphericBlend: 0.45,
    },
    {
      asset: "mountains",
      scrollFactor: 0.9,
      depth: -30,
      screenY: 1250,
      screenX: 1000,
      opacity: 0.9,
      tintKey: "mountain",
      atmosphericBlend: 0.25,
    },
  ],
  volcano: [
    {
      asset: "cloudLayerB2",
      scrollFactor: 0.01,
      depth: -95,
      screenY: 350,
      opacity: 0.35,
      tintKey: "cloud",
      atmosphericBlend: 0.9,
    },
    {
      asset: "mountains",
      scrollFactor: 0.05,
      depth: -92,
      screenY: 500,
      opacity: 0.7,
      tintKey: "mountain",
      atmosphericBlend: 0.85,
    },
    {
      asset: "cloudLayerB1",
      scrollFactor: 0.01,
      depth: -70,
      screenY: 575,
      opacity: 0.35,
      tintKey: "cloud",
      atmosphericBlend: 0.9,
    },
    {
      asset: "mountains",
      scrollFactor: 0.1,
      depth: -68,
      screenY: 675,
      screenX: 400,
      opacity: 0.75,
      tintKey: "mountain",
      atmosphericBlend: 0.6,
    },
    {
      asset: "hills",
      scrollFactor: 0.3,
      depth: -45,
      screenY: 900,
      screenX: 200,
      opacity: 0.8,
      tintKey: "hill",
      atmosphericBlend: 0.4,
    },
    {
      asset: "groundLayer1",
      scrollFactor: 0.9,
      depth: -34,
      screenY: 1400,
      opacity: 0.8,
      tintKey: "ground",
      atmosphericBlend: 0.2,
    },
  ],
  jungle: [
    {
      asset: "cloudLayerB2",
      scrollFactor: 0.01,
      depth: -95,
      screenY: 200,
      opacity: 0.4,
      tintKey: "cloud",
      atmosphericBlend: 0.7,
    },
    {
      asset: "hillsLarge",
      scrollFactor: 0.05,
      depth: -75,
      screenY: 350,
      screenX: 150,
      opacity: 0.7,
      tintKey: "hill",
      atmosphericBlend: 0.9,
    },
    {
      asset: "cloudLayerB1",
      scrollFactor: 0.08,
      depth: -70,
      screenY: 450,
      opacity: 0.35,
      tintKey: "cloud",
      atmosphericBlend: 0.55,
    },
    {
      asset: "hillsLarge",
      scrollFactor: 0.15,
      depth: -60,
      screenY: 600,
      screenX: -200,
      opacity: 0.75,
      tintKey: "hill",
      atmosphericBlend: 0.65,
    },
    {
      asset: "hills",
      scrollFactor: 0.3,
      depth: -50,
      screenY: 800,
      screenX: 100,
      opacity: 0.8,
      tintKey: "hill",
      atmosphericBlend: 0.4,
    },
    {
      asset: "groundLayer2",
      scrollFactor: 0.9,
      depth: -42,
      screenY: 1400,
      opacity: 0.8,
      tintKey: "ground",
      atmosphericBlend: 0.15,
    },
  ],
};

export function getLayerConfigs(theme: ThemeType): LayerConfig[] {
  return THEME_LAYERS[theme];
}
