export const BirdQueueConfig = {
  layout: {
    firstBirdOffset: 100,
    birdSpacing: 70,
    spawnX: -50,
  },
  walk: {
    duration: 600,
    bobFrequency: 6,
    bobAmplitude: 3,
    waddleRotation: 0.1,
    dustThreshold: 0.6,
    staggerDelay: 300,
    shiftDelay: 100,
  },
  jump: {
    anticipationDuration: 100,
    jumpDuration: 400,
    jumpHeight: 120,
    squashStretch: 0.2,
    anticipationSquashX: 1.25,
    anticipationSquashY: 0.75,
    anticipationYOffset: 5,
    fullRotation: Math.PI * 2,
  },
  bounce: {
    depth: 20,
    phase1End: 0.25,
    phase2End: 0.45,
    overshootFactor: 0.4,
    settleBounceCount: 3,
    settleAmplitude: 0.15,
  },
  idle: {
    yOffset: 4,
    duration: 1200,
    ease: "Sine.easeInOut",
  },
  trail: {
    lifespan: 250,
    speedMin: 5,
    speedMax: 15,
    scaleStart: 0.25,
    scaleEnd: 0,
    alphaStart: 0.4,
    alphaEnd: 0,
    tints: [0xffffff, 0xaaddff],
    emitThreshold: 0.5,
    offsetX: -10,
    offsetY: 10,
    depth: 21,
  },
  dust: {
    lifespan: 250,
    speedMin: 8,
    speedMax: 25,
    angleMin: 255,
    angleMax: 285,
    scaleStart: 0.15,
    scaleEnd: 0.02,
    alphaStart: 0.8,
    alphaEnd: 0,
    tints: [0x9c8b7a, 0x8b7355, 0x7a6a5a, 0x6b5b4b],
    emitThreshold: 0.6,
    offsetX: -5,
    depth: 21,
  },
  depth: 24,
} as const;
